// File generated by "melos run svg". Do not edit by hand.
// Copyright (c) 2023. The Abishek Authors. All rights reserved.

final class Asset {
  static const AssetFooter footer = AssetFooter();
}

final class AssetFooter {
  const AssetFooter();

  String get search => 'assets/footer-bin/search.svg.vec';
  String get home => 'assets/footer-bin/home.svg.vec';
  String get add => 'assets/footer-bin/add.svg.vec';
  String get chat => 'assets/footer-bin/chat.svg.vec';
  String get profile => 'assets/footer-bin/profile.svg.vec';
}
